/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GiaoDienNhom7;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapplication1.Xe;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QuanLyXe extends javax.swing.JFrame {

    listXeHoi ds = new listXeHoi();
    DefaultTableModel model;

    /**
     * Creates new form AddXe
     */
    public QuanLyXe() throws IOException {
        initComponents();
        model = (DefaultTableModel) jtbQuanLyXeHoi.getModel();
        ds.DocFileUpdate();
        ShowAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoaXe = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbQuanLyXeHoi = new javax.swing.JTable();
        txtMau = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        txtLoaiXe = new javax.swing.JTextField();
        txtTenXe = new javax.swing.JTextField();
        txtMaXe = new javax.swing.JTextField();
        txtHangXe = new javax.swing.JTextField();
        btnXoaXe1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Xe", "Tên Xe", "Loại Xe", "Giá", "Màu", "Ngày Nhập", "Hãng Xe"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Xe", "Tên Xe", "Loại Xe", "Giá", "Màu", "Ngày Nhập", "Hãng Xe"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 255, 153));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        btnThem.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/car-add.png"))); // NOI18N
        btnThem.setText("Thêm Xe");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoaXe.setBackground(new java.awt.Color(255, 0, 51));
        btnXoaXe.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnXoaXe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnXoaXe.setText("Xóa Xe");
        btnXoaXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXeActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(102, 102, 255));
        btnSua.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Edit.png"))); // NOI18N
        btnSua.setText("Sửa Thông Tin Xe");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(255, 102, 102));
        btnThoat.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.setToolTipText("");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jtbQuanLyXeHoi.setBackground(new java.awt.Color(102, 255, 51));
        jtbQuanLyXeHoi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jtbQuanLyXeHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Xe", "Tên Xe", "Loại Xe", "Giá", "Màu", "Ngày Nhập", "Hãng Xe"
            }
        ));
        jtbQuanLyXeHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbQuanLyXeHoiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtbQuanLyXeHoi);

        txtMau.setBackground(new java.awt.Color(204, 204, 255));

        txtGia.setBackground(new java.awt.Color(204, 204, 255));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("Giá:");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("Màu :");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setText("Mã Xe :");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 51, 51));
        jLabel9.setText("Tên Xe :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("Loại Xe :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setText("Ngày Nhập :");

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setText("Hãng Xe :");

        txtNgayNhap.setBackground(new java.awt.Color(204, 204, 255));

        txtLoaiXe.setBackground(new java.awt.Color(204, 204, 255));

        txtTenXe.setBackground(new java.awt.Color(204, 204, 255));

        txtMaXe.setBackground(new java.awt.Color(204, 204, 255));

        txtHangXe.setBackground(new java.awt.Color(204, 204, 255));

        btnXoaXe1.setBackground(new java.awt.Color(255, 0, 51));
        btnXoaXe1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnXoaXe1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Delete.png"))); // NOI18N
        btnXoaXe1.setText("Xóa và Cập Nhật");
        btnXoaXe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaXe1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(btnXoaXe)
                .addGap(53, 53, 53)
                .addComponent(btnSua)
                .addGap(32, 32, 32)
                .addComponent(btnXoaXe1)
                .addGap(52, 52, 52)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9)
                            .addComponent(jLabel14))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaXe, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                            .addComponent(txtLoaiXe)
                            .addComponent(txtTenXe)
                            .addComponent(txtMau)))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtMaXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtTenXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtHangXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaXe)
                    .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaXe1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Add-icon.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Quản Lý Xe");

        txtTimKiem.setBackground(new java.awt.Color(102, 255, 255));

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 51));
        btnTimKiem.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 51, 0));
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Search-icon.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel12)
                .addGap(363, 363, 363)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel5)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
         int index = ds.find(txtTimKiem.getText());
        if (index == -1) {
            JOptionPane.showConfirmDialog(rootPane, "Không tìm thấy!!!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            XeHoi ct = new XeHoi();
            ct = ds.getList().get(index);
            txtMaXe.setText(ct.getnMaXe());
            txtTenXe.setText(ct.getnTenXe());
            txtLoaiXe.setText(ct.getnLoaiXe());
            txtMau.setText(ct.getnMau());
            txtGia.setText(ct.getnGia());
            txtNgayNhap.setText(ct.getnNgayNhap());
            txtHangXe.setText(ct.getnHangXe());
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void jtbQuanLyXeHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbQuanLyXeHoiMouseClicked
        // TODO add your handling code here:
        int selectedRow = jtbQuanLyXeHoi.getSelectedRow();
        XeHoi xeHoi = new XeHoi();
        xeHoi = ds.getList().get(selectedRow);
        txtMaXe.setText(xeHoi.getnMaXe());
        txtTenXe.setText(xeHoi.getnTenXe());
        txtLoaiXe.setText(xeHoi.getnLoaiXe());
        txtMau.setText(xeHoi.getnMau());
        txtGia.setText(xeHoi.getnGia());
        txtNgayNhap.setText(xeHoi.getnNgayNhap());
        txtHangXe.setText(xeHoi.getnHangXe());
    }//GEN-LAST:event_jtbQuanLyXeHoiMouseClicked

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        new QLy_XeHoi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        try {
            if (txtMaXe.getText().length() == 0 || txtTenXe.getText().length() == 0 || txtLoaiXe.getText().length() == 0 || txtMau.getText().length() == 0 || txtGia.getText().length() == 0 || txtNgayNhap.getText().length() == 0 || txtHangXe.getText().length() == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Không được để trống!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // kiem tra ma cong trinh
                boolean flagMaXe = true;
                int index = jtbQuanLyXeHoi.getSelectedRow();
                for (int i = 0; i < ds.getList().size(); i++) {
                    XeHoi xehoi = new XeHoi();
                    xehoi = ds.getList().get(i);
                    if (i != index) {
                        if (txtMaXe.getText().equals(xehoi.getnMaXe())) {
                            flagMaXe = false;
                            break;
                        }
                    }
                }
                if (flagMaXe) {
                    XeHoi xeHoi = new XeHoi();
                    xeHoi.setnMaXe(txtMaXe.getText());
                    xeHoi.setnTenXe(txtTenXe.getText());
                    xeHoi.setnLoaiXe(txtLoaiXe.getText());
                    xeHoi.setnMau(txtMau.getText());
                    xeHoi.setnMau(txtGia.getText());
                    xeHoi.setnNgayNhap(txtNgayNhap.getText());
                    xeHoi.setnHangXe(txtHangXe.getText());
                    // sua cong trinh
                    ds.update(xeHoi, jtbQuanLyXeHoi.getSelectedRow());
                    // xoa toan bo du lieu table
                    for (int i = 0; i < ds.getList().size(); i++) {
                        model.removeRow(0);
                    }
                    // update lai du lieu
                    ShowAll();
                    ClearField();
                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Mã xe đã tồn tại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    txtMaXe.requestFocus(true);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "Dữ liệu không hợp lệ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXeActionPerformed
        // TODO add your handling code here:

        /*int row = jtbQuanLyXeHoi.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.removeRow( row );*/
        int[] index = jtbQuanLyXeHoi.getSelectedRows();
        if (index.length <= 0) {
        } else {
            int n = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn xóa?", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (n == 0) {
                int temp = 0;
                for (int i : index) {
                    model.removeRow(i - temp);
                    ds.delete(i - temp);
                    temp++;
                }
            }
        }
    }//GEN-LAST:event_btnXoaXeActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            if (txtMaXe.getText().length() == 0 || txtTenXe.getText().length() == 0 || txtLoaiXe.getText().length() == 0 || txtMau.getText().length() == 0 || txtGia.getText().length() == 0 || txtNgayNhap.getText().length() == 0 || txtHangXe.getText().length() == 0) {
                JOptionPane.showConfirmDialog(rootPane, "Không được để trống!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
            } else {
                // kiem tra ma cong trinh
                boolean flagMaXe = true;
                for (XeHoi xeHoi : ds.getList()) {
                    if (txtMaXe.getText().equals(xeHoi.getnMaXe())) {
                        flagMaXe = false;
                        break;
                    }
                }
                if (flagMaXe) {
                    XeHoi xeHoi = new XeHoi();
                    xeHoi.setnMaXe(txtMaXe.getText());
                    xeHoi.setnTenXe(txtTenXe.getText());
                    xeHoi.setnLoaiXe(txtLoaiXe.getText());
                    xeHoi.setnMau(txtMau.getText());
                    xeHoi.setnGia(txtGia.getText());
                    xeHoi.setnNgayNhap(txtNgayNhap.getText());
                    xeHoi.setnHangXe(txtHangXe.getText());
                    ds.insert(xeHoi);
                    Show();
                    ClearField();
                } else {
                    JOptionPane.showConfirmDialog(rootPane, "Mã xe đã tồn tại!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
                    txtMaXe.requestFocus(true);
                }
            }
        } catch (Exception ex) {
            JOptionPane.showConfirmDialog(rootPane, "Dữ liệu không hợp lệ!!!", "Thông báo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaXe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaXe1ActionPerformed
        // TODO add your handling code here:
         ds.sortByName();
        // Xoa toan bo du lieu trong bang
        for (int i = 0; i < ds.getList().size(); i++) {
            model.removeRow(0);
        }
        // cập nhật lai du lieu
        ShowAll();
        ClearField();
    }//GEN-LAST:event_btnXoaXe1ActionPerformed

    private void ClearField() {
        txtMaXe.setText(null);
        txtTenXe.setText(null);
        txtLoaiXe.setText(null);
        txtMau.setText(null);
        txtGia.setText(null);
        txtNgayNhap.setText(null);
        txtHangXe.setText(null);
        txtMaXe.requestFocus();
    }

    public void Show() {
        XeHoi xeHoi = new XeHoi();
        xeHoi = ds.getList().get(ds.getList().size() - 1);
        model.addRow(new Object[]{xeHoi.getnMaXe(), xeHoi.getnTenXe(), xeHoi.getnLoaiXe(), xeHoi.getnMau(), xeHoi.getnGia(), xeHoi.getnNgayNhap(), xeHoi.getnHangXe()});
    }

    private void ShowAll() {
        for (XeHoi xeHoi : ds.getList()) {
            model.addRow(new Object[]{xeHoi.getnMaXe(), xeHoi.getnTenXe(), xeHoi.getnLoaiXe(), xeHoi.getnMau(), xeHoi.getnGia(), xeHoi.getnNgayNhap(), xeHoi.getnHangXe()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyXe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QuanLyXe().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(QuanLyXe.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoaXe;
    private javax.swing.JButton btnXoaXe1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jtbQuanLyXeHoi;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtHangXe;
    private javax.swing.JTextField txtLoaiXe;
    private javax.swing.JTextField txtMaXe;
    private javax.swing.JTextField txtMau;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtTenXe;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
